parameters:
#    ahs_facebook_newscoop.example.class: AHS\FacebookNewscoopBundle\Example

services:
#    ahs_facebook_newscoop.example:
#        class: %ahs_facebook_newscoop.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
