services:
    newscoop_facebook_newscoop.hooks.listener:
        class: "Newscoop\FacebookNewscoopBundle\EventListener\HooksListener"
        arguments: ["@service_container"]
        tags:
          - { name: kernel.event_listener, event: newscoop_admin.interface.article.edit.sidebar, method: sidebar }

    newscoop_facebook_newscoop.lifecyclesubscriber:
        class: Newscoop\FacebookNewscoopBundle\EventListener\LifecycleSubscriber
        arguments:
            - @em
        tags:
            - { name: kernel.event_subscriber}