services:
    ahs_facebook_newscoop.updatearticlesubscriber:
        class: AHS\FacebookNewscoopBundle\EventListener\UpdateArticleSubscriber
        tags:
            - { name: kernel.event_subscriber}